In [2]:

import pandas as pd
import numpy as np
print(pd.__version__)

3.0.3

In [12]:
#创建一个pandas 的一维数组
series = pd.Series(['abc','23',3,4,5,6])
print(series)

0    abc
1     23
2      3
3      4
4      5
5      6
dtype: object

In [3]:
#创建一个 DataFrame，包含 一个 datetime index 且 使用date_range() 作为labeled column


#随机生成6个日期，格式如 xxxx-xx-xx
dates = pd.date_range(start='2019-01-01', periods=6)
dates
print(type(dates))
# data参数 = 随机生成(6,4)的值


# 服从标准正态分布（也叫高斯分布）的随机数。标准正态分布：均值（μ）= 0，标准差（σ）= 1。参数 (6,4)：
# 指定生成的随机数数组的形状为 6 行 4 列（二维数组）。
random_data = np.random.randn(6,4)
# index参数 = dates 日期
# columns 列 = 把ABCD字符串转换为列表
dataFrame=pd.DataFrame(random_data, index=dates, columns=list('ABCD'))
print(dataFrame)

<class 'pandas.DatetimeIndex'>
                   A         B         C         D
2019-01-01  2.110238  1.201072  0.891854 -1.262830
2019-01-02  0.024858  1.469513  1.663287  0.435999
2019-01-03  0.060831  1.106194 -0.113192  0.162285
2019-01-04 -0.510287  2.580281  0.698425  0.083868
2019-01-05  3.165384  0.072392  0.242339 -1.272103
2019-01-06 -0.210697  0.231783  0.440527 -0.745071

In [16]:
#创建dictionary key-value数据，key为列数据， value 为行数据
dictionary = {
    "A": 1.0,
    #创建Timestamp object
    "B": pd.Timestamp("20130102"),
    #创建Series object
    "C": pd.Series(1,index=list(range(4)),dtype='float32'),
    "D": np.array([3]*4,dtype='int32'),
    #创建Categorical object
    "E": pd.Categorical(['test','train','test','train']),
}
df2 = pd.DataFrame(dictionary)
print(df2)
print(df2.dtypes)

     A          B    C  D      E
0  1.0 2013-01-02  1.0  3   test
1  1.0 2013-01-02  1.0  3  train
2  1.0 2013-01-02  1.0  3   test
3  1.0 2013-01-02  1.0  3  train
A          float64
B    datetime64[s]
C          float32
D            int32
E         category
dtype: object

In [19]:
#获取头部前五行，默认为5
dataFrame.head()
#获取头部前3行
dataFrame.head(3)

#获取尾部5行数据，默认为5
dataFrame.tail()
dataFrame.tail(2)

                   A         B         C         D
2019-01-05 -0.305553 -1.196850 -1.746516 -0.727617
2019-01-06 -0.925391  0.561239  1.027847 -0.706870

In [22]:
index = dataFrame.index
print(index)
columns = dataFrame.columns
print(columns)

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [23]:
numpy = dataFrame.to_numpy()
print(numpy)

[[ 0.89074013 -0.15682041  1.42052291 -0.72319794]
 [-0.55797477  0.14773323  0.59073843  0.33572053]
 [ 1.2199755   0.48583508 -1.02552349 -0.52119313]
 [-1.84703532 -0.33720239  0.3212119  -1.41331376]
 [-0.30555281 -1.1968503  -1.74651646 -0.72761717]
 [-0.9253912   0.56123887  1.027847   -0.70686985]]

In [25]:
dataFrame.describe()
dataFrame.describe(include='all')

df2.T

,0,1,2,3
A,1.0,1.0,1.0,1.0
B,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00
C,1.0,1.0,1.0,1.0
D,3,3,3,3
E,test,train,test,train

In [32]:
#列的顺序按列名排序(从D 到A )，行顺序不变，降序排序
dataFrame.sort_index(axis=1, ascending=False)
#列的顺序按列名排序(从A 到D )，行顺序不变，降序排序
dataFrame.sort_index(axis=1, ascending=True)
#行的顺序按行名排序(从01-06 到 01-01 )，列顺序不变，倒序
dataFrame.sort_index(axis=0, ascending=False)

                   A         B         C         D
2019-01-06 -0.925391  0.561239  1.027847 -0.706870
2019-01-05 -0.305553 -1.196850 -1.746516 -0.727617
2019-01-04 -1.847035 -0.337202  0.321212 -1.413314
2019-01-03  1.219976  0.485835 -1.025523 -0.521193
2019-01-02 -0.557975  0.147733  0.590738  0.335721
2019-01-01  0.890740 -0.156820  1.420523 -0.723198

In [33]:
dataFrame.sort_values(by='A')
#设置特定某一列进行排序
dataFrame.sort_values(by='A', ascending=False)

                   A         B         C         D
2019-01-03  1.219976  0.485835 -1.025523 -0.521193
2019-01-01  0.890740 -0.156820  1.420523 -0.723198
2019-01-05 -0.305553 -1.196850 -1.746516 -0.727617
2019-01-02 -0.557975  0.147733  0.590738  0.335721
2019-01-06 -0.925391  0.561239  1.027847 -0.706870
2019-01-04 -1.847035 -0.337202  0.321212 -1.413314